import type { Metadata } from "next";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Cookie Policy",
  description:
    "Information on cookie usage at waicode.es. This site does not install tracking or advertising cookies.",
  alternates: { canonical: "/en/cookies" },
};

export default function CookiePolicyEN() {
  return (
    <>
      <Navbar />
      <main className="mx-auto max-w-3xl px-4 py-24 sm:px-6 lg:px-8">
        <h1 className="text-3xl font-bold tracking-tight text-ink sm:text-4xl">
          Cookie Policy
        </h1>
        <p className="mt-3 text-sm text-slate-550">Last updated: June 2026</p>

        <div className="mt-10 space-y-10 text-[15px] leading-relaxed text-slate-550">

          <section>
            <h2 className="text-lg font-bold tracking-tight text-ink">
              1. What are cookies?
            </h2>
            <p className="mt-3">
              Cookies are small text files that websites store on the user&rsquo;s
              device in order to save browsing preferences, sessions or
              statistical information.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold tracking-tight text-ink">
              2. Does this website use cookies?
            </h2>
            <p className="mt-3">
              The website{" "}
              <strong className="font-semibold text-ink">waicode.es</strong>{" "}
              does not install its own tracking, analytics or advertising
              cookies.
            </p>
            <p className="mt-3">
              The only cookies that may be present are{" "}
              <strong className="font-semibold text-ink">
                technical or session cookies
              </strong>{" "}
              generated by the browser itself or by the hosting infrastructure,
              which are necessary for the Website to function correctly. These
              cookies are strictly necessary and do not require user consent
              under Article 22.2 of the LSSI-CE.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold tracking-tight text-ink">
              3. Cookie types
            </h2>
            <div className="mt-4 overflow-hidden rounded-2xl ring-1 ring-ink/8">
              <table className="w-full text-sm">
                <thead className="bg-ink/[0.03]">
                  <tr>
                    <th className="px-4 py-3 text-left font-semibold text-ink">
                      Type
                    </th>
                    <th className="px-4 py-3 text-left font-semibold text-ink">
                      Purpose
                    </th>
                    <th className="px-4 py-3 text-left font-semibold text-ink">
                      Management
                    </th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-ink/5">
                  <tr>
                    <td className="px-4 py-3">Technical / session</td>
                    <td className="px-4 py-3">Basic server operation</td>
                    <td className="px-4 py-3">Browser-native</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </section>

          <section>
            <h2 className="text-lg font-bold tracking-tight text-ink">
              4. Third-party cookies
            </h2>
            <p className="mt-3">
              The Website does not load third-party scripts that install cookies
              on your device. Typefaces are served locally from our own server,
              and videos are self-hosted files (not YouTube or external platform
              embeds).
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold tracking-tight text-ink">
              5. Managing and disabling cookies
            </h2>
            <p className="mt-3">
              You can configure or disable cookies from your browser settings.
              Please note that disabling technical cookies may affect the
              functioning of some websites.
            </p>
            <ul className="mt-4 space-y-2">
              <li>
                <strong className="font-semibold text-ink">Chrome:</strong>{" "}
                Settings › Privacy and security › Cookies and other site data
              </li>
              <li>
                <strong className="font-semibold text-ink">Firefox:</strong>{" "}
                Options › Privacy &amp; Security › Cookies and Site Data
              </li>
              <li>
                <strong className="font-semibold text-ink">Safari:</strong>{" "}
                Preferences › Privacy
              </li>
              <li>
                <strong className="font-semibold text-ink">Edge:</strong>{" "}
                Settings › Privacy, search, and services › Cookies
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold tracking-tight text-ink">
              6. Further information
            </h2>
            <p className="mt-3">
              For any questions about cookie usage, message us on WhatsApp (+34
              610 097 562). You can also find further information from the
              Spanish Data Protection Agency (
              <a
                href="https://www.aepd.es"
                target="_blank"
                rel="noopener noreferrer"
                className="font-medium text-brand-600 underline underline-offset-2 hover:text-brand-700"
              >
                www.aepd.es
              </a>
              ).
            </p>
          </section>

        </div>
      </main>
      <Footer locale="en" />
    </>
  );
}
